### ISSUE TITLE
Erro var.private_subnet_ids)}"]

### ISSUE THREAD

**Issue by estefancaique** [turnerlabs/terraform-aws-elasticache-redis#3]
Dou you have this error 
│ Error: Incorrect attribute value type
│
│   on redis.tf line 17, in resource "aws_elasticache_subnet_group" "default":
│   17:   subnet_ids  = ["${split(",", var.private_subnet_ids)}"]
│     ├────────────────
│     │ var.private_subnet_ids will be known only after apply
│
│ Inappropriate value for attribute "subnet_ids": element 0: string required.

**Comment by awlawl** [comment]
This module is now up to date and tested with modern terraform 1.2.0 and aws provider v4.24.0.
